#!/bin/bash
#

extargs="--png --nsteps=5000 --burnfrac=0.2"
# extargs="--png"
fmfit="python utils/fit_uv_ext_fm90.py"

rm -f fits/*FM90.h5

#for CLIST in iue stis1 stis2 stis3
for CLIST in stis3
do
  cfile="data/smc_stars_${CLIST}.dat"
  while read -r line;
  do
    echo $line
    $fmfit fits/"$line"_ext.fits $extargs
    $fmfit fits/"$line"_ext_forecor.fits $extargs
    $fmfit fits/"$line"_ext_forecor_plus.fits $extargs
    $fmfit fits/"$line"_ext_forecor_minus.fits $extargs
  done < $cfile
done
