#!/bin/bash
#

extargs="--png --nsteps=10000 --burnfrac=0.4"
# extargs="--png"
fmfit="python utils/fit_uv_ext_fm90.py"

rm -f fits/*FM90.h5

while read -r line;
do
  echo $line
  $fmfit fits/"$line"_ext.fits $extargs
done < "data/smc_stars_stis1.dat"

# $fmfit fits/2dfs0413_ext.fits $extargs
